-- Migracion opcional para incidencias
ALTER TABLE INCIDENCIA ADD COLUMN IF NOT EXISTS tipo_incidencia VARCHAR(50) NOT NULL DEFAULT 'otro';
ALTER TABLE INCIDENCIA ADD COLUMN IF NOT EXISTS origen VARCHAR(20) NOT NULL DEFAULT 'maquinista';
ALTER TABLE INCIDENCIA ADD CONSTRAINT incidencia_origen_chk CHECK (origen IN ('maquinista', 'iot'));
ALTER TABLE INCIDENCIA ADD COLUMN IF NOT EXISTS afecta_pasajero BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE INCIDENCIA ADD COLUMN IF NOT EXISTS resolucion TEXT;
ALTER TABLE INCIDENCIA ADD COLUMN IF NOT EXISTS fecha_resolucion TIMESTAMP;
